CenterMap_weight: 160.0
FOV: 60
GPUS: 0,1,2,3,4,5,6,7
HMloss_type: MSE
MPJPE_weight: 200.0
PAMPJPE_weight: 360.0
PCK_thresh: 150
P_KP2D_weight: 400.0
Pose_weight: 80.0
Prior_weight: 1.6
Rot_type: 6D
Shape_weight: 6.0
Synthetic_occlusion_ratio: 0
adjust_lr_epoch: []
adjust_lr_factor: 0.1
backbone: resnet101
batch_size: 16
beta_dim: 10
calc_PVE_error: false
calc_pck: false
cam_dim: 3
center_def_kp: true
centermap_conf_thresh: 0.2
centermap_size: 16
character: smpl
collision_aware_centermap: true
collision_factor: 0.2
color_jittering_ratio: 0.2
configs_yml: configs/v1.yml
dataset: pw3d
dataset_rootdir: /z/home/mkhoshle/dataset/
dec_layers: 6
deconv_num: 0
dilation: false
dim_feedforward: 1024
distillation_learning: false
distributed_training: false
dropout: 0.1
enc_layers: 6
epoch: 150
eval: true
eval_2dpose: false
eval_datasets: pw3d
exp: HOI_VANILLA
f: null
fast_eval_iter: -1
fine_tune: false
fix_backbone_training_scratch: true
focal_length: 443.4
fps_save: 24
head_block_num: 2
hidden_dim: 256
homogenize_pose_space: true
input_size: 512
inputs: null
interactive_vis: false
kernel_sizes:
- 5
learn_2dpose: false
learn_AE: false
learn_kp2doffset: false
local_rank: 0
log_path: /z/home/mkhoshle/log/
loss_thresh: 1000
lr: 1.0e-05
lr_backbone: 1.0e-05
make_tracking: false
masks: false
master_batch_size: -1
match_preds_to_gts_for_supervision: true
matching_mode: all
max_person: 64
max_supervise_num: -1
merge_smpl_camera_head: false
mesh_cloth: '031'
model_path: None
model_precision: fp16
model_return_loss: true
model_version: 1
multi_person: true
new_training: false
nheads: 8
num_feature_levels: 1
nvxia_model_path: /z/home/mkhoshle/Human_object_transform/model_data/characters/nvxia
nw: 4
nw_eval: 4
optimizer_type: Adam
output_dir: demo/image_results
partial_load: false
perspective_proj: false
position_embedding: learned
pre_norm: true
print_freq: 50
renderer: pytorch3d
resnet_pretrain: /z/home/mkhoshle/Human_object_transform/trained_models/resnet101-5d3b4d8f.pth
rot_dim: 6
rotate_prob: 0.2
sample_prob_dict:
  pw3d: 1
save_centermap: true
save_dict_results: true
save_dir: ./results
save_mesh: true
save_visualization_on_img: true
show_largest_person_only: false
show_mesh_stand_on_image: false
shuffle_crop_mode: true
shuffle_crop_ratio_2d: 0.1
shuffle_crop_ratio_3d: 0.4
smpl_J_reg_extra_path: /z/home/mkhoshle/Human_object_transform/model_data/parameters/smpl/J_regressor_extra.npy
smpl_J_reg_h37m_path: /z/home/mkhoshle/Human_object_transform/model_data/parameters/smpl/J_regressor_h36m.npy
smpl_joint_num: 22
smpl_mesh_root_align: true
smpl_model_path: /z/home/mkhoshle/Human_object_transform/model_data/parameters/smpl
smpl_uvmap: /z/home/mkhoshle/Human_object_transform/model_data/parameters/smpl/smpl_vt_ft.npz
soi_camera: far
supervise_cam_params: false
supervise_global_rot: false
tab: resnet101_cm16_V1
temporal_optimization: false
test_interval: 2000
top_n_error_vis: 6
track_attention: false
track_memory_usage: false
use_coordmaps: true
use_eft: true
use_wandb: true
val_batch_size: 64
voc_dir: /z/home/mkhoshle/dataset/VOCdevkit/VOC2012/
wardrobe: /z/home/mkhoshle/Human_object_transform/model_data/wardrobe
weight_decay: 1.0e-06
