ARGS:
 tab: 'V1' 
 dataset: 'pw3d'
 GPUS: 0
 distributed_training: False
 model_version: 1
 pretrain: 'imagenet'
 match_preds_to_gts_for_supervision: True
 master_batch_size: -1
 epoch: 150
 val_batch_size: 4      
 batch_size: 16
 nw: 4                
 nw_eval: 4             
 lr: 0.00001
 use_wandb: True
 exp: 'HOI_pool_64_relu_fixed_BB'              # experiment name
 save_dir: './results'           # Path to results directory
 
 hidden_dim: 256                  # This should be divisible by the number of heads
 hidden_dim_pos: 256
 position_embedding: "learned"
 lr_backbone: 0.00001
 masks: False
 num_feature_levels: 1
#  backbone: 'resnet'
 backbone: 'resnet_fpn_backbone'     # This is for Faster-RCNN
 dilation: False
 dropout: 0.1
 nheads: 8
 dim_feedforward: 256
 deformable: True


 enc_layers: 3
 dec_layers: 3
 pre_norm: True
 track_attention: False

 fine_tune: False
 partial_load: False
 fix_backbone_training_scratch: True
 eval: True
 supervise_global_rot: False

 model_return_loss: True
 collision_aware_centermap: True
 collision_factor: 0.2
 homogenize_pose_space: True
 shuffle_crop_mode: True
 shuffle_crop_ratio_2d: 0.1
 shuffle_crop_ratio_3d: 0.4

 merge_smpl_camera_head: False
 head_block_num: 2

 centermap_size: 32
 centermap_conf_thresh: 0.2
#  resnet_pretrain: "trained_models/pretrain_resnet.pkl"
 resnet_pretrain: "trained_models/checkpoint_det_ResNet_Backbone.pkl"  # This is for Faster-RCNN
#  hrnet_pretrain: "trained_models/pretrain_hrnet.pkl"
#  model_path: "/z/home/mkhoshle/checkpoints/resnet_cm32_V1_on_gpu0,1,2,3,4,5,6,7_val/resnet_cm32_V1_epoch_8.pkl"
 model_path: ""
 output_dir: 'demo/image_results'
 save_mesh: True
 save_centermap: True
 save_dict_results: True

loss_weight:
  MPJPE: 200.
  PAMPJPE: 360.
  P_KP2D: 400.
  Pose: 80.
  Shape: 6.
  Prior: 1.6
  CenterMap: 160.

sample_prob:
 # cmup: 1.0
 pw3d: 1.0
 # crowdhuman: 0.2
 # crowdpose: 0.24
 # coco: 0.2
 # lsp: 0.16
 # mpii: 0.2