
ARGS:
 tab: 'V1' 
 # dataset: 'cmup'
 dataset: 'pw3d'
 GPUS: 0,1,2,3,4,5,6,7
 distributed_training: False
 model_version: 1
 match_preds_to_gts_for_supervision: True
 master_batch_size: -1
 epoch: 150
 val_batch_size: 4      
 batch_size: 4
 nw: 4                
 nw_eval: 4             
 lr: 0.00001
 use_wandb: False
 exp: 'HOI_VANILLA'              # experiment name
 save_dir: './results'           # Path to results directory
 
 hidden_dim: 64                  # This should be divisible by the number of heads
 hidden_dim_pos: 64
 position_embedding: "learned"
 lr_backbone: 0.00001
 masks: False
 num_feature_levels: 1
 backbone: 'resnet_fpn_backbone'     
 dilation: False
 dropout: 0.1
 nheads: 4
 dim_feedforward: 1024
 enc_layers: 6
 dec_layers: 6
 pre_norm: True
 track_attention: False

 fine_tune: False
 partial_load: False
 fix_backbone_training_scratch: False
 eval: True
 supervise_global_rot: False

 model_return_loss: True
 collision_aware_centermap: True
 collision_factor: 0.2
 homogenize_pose_space: True
 shuffle_crop_mode: True
 shuffle_crop_ratio_2d: 0.1
 shuffle_crop_ratio_3d: 0.4

 merge_smpl_camera_head: False
 head_block_num: 2

 centermap_size: 8
 centermap_conf_thresh: 0.2

 resnet_pretrain: "trained_models/checkpoint_det_ResNet_Backbone.pkl"
#  hrnet_pretrain: "trained_models/pretrain_hrnet.pkl"
 model_path: None
 output_dir: 'demo/image_results'
 save_mesh: True
 save_centermap: True
 save_dict_results: True

loss_weight:
  MPJPE: 200.
  PAMPJPE: 360.
  P_KP2D: 400.
  Pose: 80.
  Shape: 6.
  Prior: 1.6
  CenterMap: 160.

sample_prob:
 pw3d: 1.0
 # cmup: 1.0
 # pw3d: 1.0
 # crowdhuman: 0.2
 # crowdpose: 0.24
 # coco: 0.2
 # lsp: 0.16
 # mpii: 0.2